version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    volumes:
      - prim-id-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "55433:5432"

volumes:
  prim-id-postgres-data: